import { createClient } from '@supabase/supabase-js'

export const supabase = createClient('https://mizfzzxawliafsnkjrnn.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pemZ6enhhd2xpYWZzbmtqcm5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDIyNDgyNTcsImV4cCI6MjAxNzgyNDI1N30.aStu8f7wyJICS9FepOyndSdsM2atEeb2iMdmJrCntzk')